### ISSUE TITLE
[4] add SSL connection steps to docs

### ISSUE THREAD

**Issue by sbeal333** [dsg-innosource/foreflow-docs#6]
# Description
Per Tom we should add instructions to the docs about how to set up a secure connection to the foreflow database with the following tools:

- DBeaver
- MySQL Workbench
- Sequel Pro

# Tasks

- [ ] add docs for DBeaver
- [ ] add docs for MySQL Workbench
- [ ] add docs for SQL Pro
